services:
  - type: web
    name: one-thousand-one-nights
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app

    envVars:
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}

