services:
  - type: web
    name: one-thousand-one-nights
    env: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}

